version: '3.3'

services:
  cicd-deployer:
    build: .
    ports:
      - "60414:60414"
    container_name: cicd-deployer
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      API_KEY_HEADER: X-API-Key
      SCRIPT_PATH: ./example_run.sh
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 60414"
